version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  selenium-test:
    image: selenium_demo:latest
    container_name: selenium_demo
    depends_on:
      - firefox
      - chrome
    environment:
      - SELENIUM_HUB=selenium-hub
      - BROWSER_NAME=Chrome
    volumes:
      - ./demo_volume/selenium_docker/target:/selenium-docker/target
